### ISSUE TITLE
How to use the component with a individual account without domain or google workspace account 

### ISSUE THREAD

**Issue by ebarolo** [macMikey/4d-google-docs#49]
Hi, can we use the component with an individual account, without domain or google workspace account?

 If yes, how do we set up the oath parameters ?

Thank you 

Regards

**Comment by macMikey** [comment]
howdy.
not as it stands. it was designed for using a google service account, so 4d server could operate, easier.
you could probably graft the 4D Netkit oauth solution on to get the tokens. 4D netkit supports both service accounts and individual accounts.

If you decide to tackle this issue, please issue a PR to make the library better.

**Comment by macMikey** [comment]
@ebarolo have you looked at this?
i think it might be possible, from 4D 20R7, forward, to use 4D NetKit to handle the oauth for a normal user accont, and then pass that object into here. it might take a bit of extra handling, around the expiration/renewal of the tokens.
